DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS department;

CREATE TABLE department (
                            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            name VARCHAR(255) NOT NULL,
                            created_at TIMESTAMP,
                            created_by VARCHAR(255),
                            updated_at TIMESTAMP,
                            updated_by VARCHAR(255)
);

CREATE TABLE employee (
                          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          name VARCHAR(255) NOT NULL,
                          department_id BIGINT,
                          created_at TIMESTAMP,
                          created_by VARCHAR(255),
                          updated_at TIMESTAMP,
                          updated_by VARCHAR(255),

                          CONSTRAINT fk_department FOREIGN KEY (department_id)
                              REFERENCES department(id)
                              ON DELETE SET NULL
);